application: saint-laurent
version: 1
runtime: go
api_version: go1

handlers:
- url: /api/.*
  script: _go_app
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /
  static_dir: static

skip_files:
- ^(.*/)?.*/static/bower_components/web-component-tester/.*$
- ^(.*/)?.*/static/bower_components/accessibility-developer-tools/.*$
- ^(.*/)?.*/static/bower_components/async/.*$
- ^(.*/)?.*/static/bower_components/chai/.*$
- ^(.*/)?.*/static/bower_components/lodash/.*$
- ^(.*/)?.*/static/bower_components/mocha/.*$
- ^(.*/)?.*/static/bower_components/sinon-chai/.*$
- ^(.*/)?.*/static/bower_components/sinonjs/.*$
- ^(.*/)?.*/static/bower_components/stacky/.*$
- ^(.*/)?.*/static/*/bower\.json$