application: saint-laurent
version: 1
runtime: go
api_version: go1

handlers:
- url: /api/.*
  script: _go_app
- url: /
  static_files: public/index.html
  upload: public/index.html
- url: /
  static_dir: public

skip_files:
- ^(.*/)?.*/static/bower_components/.*$
- ^(.*/)?.*/static/*/bower\.json$
- ^(.*/)?.*/node_modules/.*$
- ^(.*/)?.*/package\.json$
